### ISSUE TITLE
ローカル環境でのE2Eテストに失敗する

### ISSUE THREAD

**Issue by harachanx** [tsuemura/practical-guide-for-test-automation-support#4]
## 問題の概要
「6-5-1　様々な環境で実行するための準備を整える」で、
ローカル環境（`BASE_URL=http://localhost:8080`）でE2Eテストを実行すると、テストが失敗します。
一方、デプロイ環境（例：`BASE_URL=https://fastify-webapp-sample.takuyasuemura.dev`）では正常にテストが実行されます。

## 再現手順
書籍に掲載されている手順に従っております。
1. `.env`ファイルで`BASE_URL=http://localhost:8080`を設定
2. `npm run test:e2e`を実行

## エラーログ

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at onSendEnd (/Users/xxx/Dev/fastify-webapp-sample/node_modules/fastify/lib/reply.js:571:9)
    at wrapOnSendEnd (/Users/xxx/Dev/fastify-webapp-sample/node_modules/fastify/lib/reply.js:537:5)
    at next (/Users/xxx/Dev/fastify-webapp-sample/node_modules/fastify/lib/hooks.js:213:7)
    at /Users/xxx/Dev/fastify-webapp-sample/node_modules/@fastify/session/lib/fastifySession.js:190:9
    at /Users/xxx/Dev/fastify-webapp-sample/node_modules/@fastify/session/lib/session.js:171:9
    at /Users/xxx/Dev/fastify-webapp-sample/node_modules/connect-pg-simple/index.js:396:24
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

クライアント側のエラー:
```
localhost refused to connect.
ERR_CONNECTION_REFUSED
```

こちらで必要な手順が漏れている可能性もありますが、原因わかりましたらご教示ください！

**Comment by ytak-sagit** [comment]
私も同様のエラーがローカル環境で発生しております。
```bash
node:_http_server:345
    throw new ERR_HTTP_HEADERS_SENT('write');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at onSendEnd (/app/node_modules/fastify/lib/reply.js:571:9)
    at wrapOnSendEnd (/app/node_modules/fastify/lib/reply.js:537:5)
    at next (/app/node_modules/fastify/lib/hooks.js:213:7)
    at /app/node_modules/@fastify/session/lib/fastifySession.js:190:9
    at /app/node_modules/@fastify/session/lib/session.js:171:9
    at /app/node_modules/connect-pg-simple/index.js:396:24
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by tsuemura** [comment]
@Gyozadaigaku @ytak-sagit 確認が遅れて申し訳ありません！
こちらで再現しないのですが、差し支えなければお二人の動作環境（OS、NodeJSのバージョンなど）を伺っても良いでしょうか？

**Comment by tsuemura** [comment]
別のIssueから、 @ytak-sagit さんの環境はWSLでしょうかね。

> 環境
> 以下の環境で発生
> 
> WSL2 + Ubuntu 22.04
> Node.js: v20.16.0
> npm: v10.8.1
> allure-codeceptjs@2.15.1

**Comment by harachanx** [comment]
@tsuemura
> 差し支えなければお二人の動作環境（OS、NodeJSのバージョンなど）を伺っても良いでしょうか？

macOS Sonoma 14.4 / NodeJS v22.6.0
です！

ちなみに、書籍内で使われているNodeJSのバージョン（v20.14.0）でも同様の事象が発生するみたいでした...！

**Comment by ytak-sagit** [comment]
@tsuemura  
> 差し支えなければお二人の動作環境（OS、NodeJSのバージョンなど）を伺っても良いでしょうか？
  
> 別のIssueから、 @ytak-sagit さんの環境はWSLでしょうかね。
> 
> > 環境
> > 以下の環境で発生
> > WSL2 + Ubuntu 22.04
> > Node.js: v20.16.0
> > npm: v10.8.1
> > allure-codeceptjs@2.15.1

上記、記載頂いた通りです！  
  
ちなみに記憶の限りでは、第5章で最初にサンプルアプリをローカルで動かした際は、事象が発生していませんでした。

**Comment by tsuemura** [comment]
@Gyozadaigaku @ytak-sagit こちらの件、解決に時間が掛かっておりまして申し訳ありません。
こちらで状況が再現できず、苦慮しております。

ログを見る限りですと、サンプルアプリケーションがHTTPレスポンスを返した「後」に、もう一度HTTPヘッダを返そうとして失敗しているようです。
そのため、E2Eテスト側ではなく、サンプルアプリケーション側の問題です。
ですが、6-5-1まででサンプルアプリケーションに手を入れているところは無かったはずなので、邪魔なプロセスが生きていたり、コードの中のエラーハンドリング箇所で問題が起きているのではないかと推測しています。

トラブルシュートのため、お手数ですが、以下の点を試してみて頂いてもよろしいでしょうか？

1. `npm run dev` コマンドでアプリケーションを単体で立ち上げ、ブラウザから `http://localhost:8080` にアクセスした場合、正常に開けるかどうかを確認する。
2. Docker上で動いているPostgreSQLコンテナを一度停止する。アプリケーションのルートディレクトリ上で `docker compose down` コマンドを実行すると停止します。その後、改めて `npm run test:e2e` または `npm run dev` コマンドで結果を確認してみてください。
3. PC/Mac自体を一度シャットダウンする。WSLの場合は、LinuxだけのシャットダウンでもOKなはずです。

**Comment by tsuemura** [comment]
また、こちらで確認に使用しているのは https://github.com/tsuemura/fastify-webapp-sample リポジトリの ch06 ブランチです。もし可能でしたら、お手元のコードで `git checkout ch06` していただき、同様に問題が起きるかご確認頂けますと大変幸いです。

**Comment by ytak-sagit** [comment]
@tsuemura  
調査頂きありがとうございます！  
`ch06`ブランチにて、以下、確認しました。

> 1. `npm run dev` コマンドでアプリケーションを単体で立ち上げ、ブラウザから `http://localhost:8080` にアクセスした場合、正常に開けるかどうかを確認する。

- 正常に開けます。
  - `http://localhost:8080/items` へリダイレクトされ、商品一覧画面が表示されます。

> 2. Docker上で動いているPostgreSQLコンテナを一度停止する。アプリケーションのルートディレクトリ上で `docker compose down` コマンドを実行すると停止します。その後、改めて `npm run test:e2e` または `npm run dev` コマンドで結果を確認してみてください。

- `http://localhost:8080` にアクセス後、`http://localhost:8080/items` へリダイレクトされ、商品一覧画面が表示されます。
- その後、テストコードにてadminでのログインを試行した際、同様のエラーが発生しました。（エラーログの内容も同じ）
  - `npm run dev` 実行後、手動でadminでのログインを試行した場合も、同様のエラーとなります。
  - 再度 `npm run dev` 実行後、adminでのログインがされた状態となっているため、手動でログアウトを試行した場合も、同様のエラーとなります。
  - 「商品の追加」や「商品の引き渡し」などは、エラーにならず成功しました。（試行回数1回ですが...）

> 3. PC/Mac自体を一度シャットダウンする。WSLの場合は、LinuxだけのシャットダウンでもOKなはずです。

- WSL環境で実行していますので、`wsl --shutdown` にてシャットダウン。
- その後、再度 `npm run test:e2e` を実行してみましたが、同様のエラーとなりました。

一応、実行時のコマンドとエラーログの詳細を添付いたします。（長いため折りたたんでいます）
<details>

```bash
$ HEADLESS=true npm run test:e2e

> fastify-react-sample@1.0.0 test:e2e
> npx start-server-and-test dev http://localhost:8080 'cd e2e && npm run test'

1: starting server using command "npm run dev"
and when url "[ 'http://localhost:8080' ]" is responding with HTTP status code 200
running tests using command "cd e2e && npm run test"


> fastify-react-sample@1.0.0 dev
> nodemon src/index.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,mjs,ejs,js,json,graphql
[nodemon] starting `node src/index.js`
Server listening at http://0.0.0.0:8080

> e2e@1.0.0 test
> codeceptjs run --steps

CodeceptJS v3.3.7 #StandWithUkraine
Using test root "/app/e2e"

一般的なエラーのテスト --
  ユーザーが存在しないURLにアクセスすると、エラーメッセージと商品一覧へのリンクが表示される
    I am on page "/undefined"
    I see "お探しのページは見つかりませんでした。"
    I click "商品一覧へ戻る"
    I see in title "商品一覧"
  ✔ OK in 1120ms

スモークテスト --
  example.comにアクセスする
    I am on page "https://example.com"
    I see "Example Domain"
  ✔ OK in 997ms

  Webサイトを開きログインする
    I am on page "/"
    I click "ログインする"
    I fill field "ユーザー名", "user1"
    I fill field "パスワード", "super-strong-passphrase"
    I click "ログイン"
node:_http_server:345
    throw new ERR_HTTP_HEADERS_SENT('write');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at onSendEnd (/app/node_modules/fastify/lib/reply.js:571:9)
    at wrapOnSendEnd (/app/node_modules/fastify/lib/reply.js:537:5)
    at next (/app/node_modules/fastify/lib/hooks.js:213:7)
    at /app/node_modules/@fastify/session/lib/fastifySession.js:190:9
    at /app/node_modules/@fastify/session/lib/session.js:171:9
    at /app/node_modules/connect-pg-simple/index.js:396:24
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v20.16.0
[nodemon] app crashed - waiting for file changes before starting...
    I see "user1 さん"
  ✖ FAILED in 2258ms


-- FAILURES:

  1) スモークテスト
       Webサイトを開きログインする:

      expected web application to include "user1 さん"
      + expected - actual

      +user1 さん
      
  
  
  Scenario Steps:
  - I.see("user1 さん") at Test.<anonymous> (./smoke_test.js:14:5)
  - I.click("ログイン") at Test.<anonymous> (./smoke_test.js:13:5)
  - I.fillField("パスワード", "super-strong-passphrase") at Test.<anonymous> (./smoke_test.js:12:5)
  - I.fillField("ユーザー名", "user1") at Test.<anonymous> (./smoke_test.js:11:5)
  - I.click("ログインする") at Test.<anonymous> (./smoke_test.js:10:5)
  - I.amOnPage("/") at Test.<anonymous> (./smoke_test.js:9:5)
  
  Artifacts:
  - screenshots: /app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0000.png,/app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0001.png,/app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0002.png,/app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0003.png,/app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0004.png,/app/e2e/output/record_454d187ec3888c7134731f2985d4d593/0005.png
  - screenshot: /app/e2e/output/Webサイトを開きログインする.failed.png


  FAIL  | 2 passed, 1 failed   // 5s
Run with --verbose flag to see complete NodeJS stacktrace
◉ Step-by-step preview: file:///app/e2e/output/records.html
Error: Command failed with exit code 1: cd e2e && npm run test
    at makeError (/app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: cd e2e && npm run test',
  command: 'cd e2e && npm run test',
  escapedCommand: '"cd e2e && npm run test"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

</details>

**Comment by ytak-sagit** [comment]
@tsuemura  
続報です。  
前述の実行結果から、ログイン/ログアウト周りが怪しそうかな？と推測し、  
`src/routes/login.js` を以下のように修正してみたところ、ローカル実行でエラーが発生しなくなりました。

#### 変更点
- `post /login` について、一見すると `/items` へのリダイレクトが2回発生するように見受けられました。  
  - 頂いた以下の考察も参考に、この2回リダイレクトが失敗するような振る舞いに繋がっているのでは？と推測し、`successRedirect` を削除し、認証成功後に自動でリダイレクトされないようにしてみました。  
  > ログを見る限りですと、サンプルアプリケーションがHTTPレスポンスを返した「後」に、もう一度HTTPヘッダを返そうとして失敗しているようです。
- 上記だけだとまだエラーが発生しており、他のコードを参考に、`reply.redirect` の前に `await` を付与してみました。

何かしら調査のご参考になれば幸いです。
※当方、fastify を全く知らず、よろしくない書き方等していましたら申し訳ないです。。。

```diff js
export default async function loginRoutes(server, options) {
  const { passport } = options

  server.get("/login", async (request, reply) => {
    if (request.user) {
      await reply.redirect(302, "/items")
    }
    await reply.view("/src/views/login.ejs");
  });

  server.post(
    "/login",
    {
      preValidation: passport.authenticate("local", {
-       successRedirect: "/items",
        authInfo: false,
      }),
    },
    async (request, reply) => {
-     reply.redirect("/items");
+     await reply.redirect("/items")
    }
  );

  server.get(
    '/logout',
    async (request, reply) => {
      await request.logOut()
-     reply.redirect(302, '/login')
+     await reply.redirect(302, '/login')
    }
  )
}
```

**Comment by harachanx** [comment]
@tsuemura 
調査おつかれさまです！

> 1. `npm run dev` コマンドでアプリケーションを単体で立ち上げ、ブラウザから `http://localhost:8080` にアクセスした場合、正常に開けるかどうかを確認する。
> 2. Docker上で動いているPostgreSQLコンテナを一度停止する。アプリケーションのルートディレクトリ上で `docker compose down` コマンドを実行すると停止します。その後、改めて `npm run test:e2e` または `npm run dev` コマンドで結果を確認してみてください。
> 3. PC/Mac自体を一度シャットダウンする。WSLの場合は、LinuxだけのシャットダウンでもOKなはずです。

僕も`ch06 `ブランチで試したところ、1.~3. まで @ytak-sagit さんと同じ結果でした...！
取り急ぎご共有です。

**Comment by harachanx** [comment]
@tsuemura 
> #### 変更点
> * `post /login` について、一見すると `/items` へのリダイレクトが2回発生するように見受けられました。
>   
>   * 頂いた以下の考察も参考に、この2回リダイレクトが失敗するような振る舞いに繋がっているのでは？と推測し、`successRedirect` を削除し、認証成功後に自動でリダイレクトされないようにしてみました。
>   
>   > ログを見る限りですと、サンプルアプリケーションがHTTPレスポンスを返した「後」に、もう一度HTTPヘッダを返そうとして失敗しているようです。
> * 上記だけだとまだエラーが発生しており、他のコードを参考に、`reply.redirect` の前に `await` を付与してみました。

@ytak-sagit さんが提供してくださったこちらの情報を元にコードを修正したところ、ローカル実行でエラーが発生しなくなりました！

**Comment by tsuemura** [comment]
@ytak-sagit ありがとうございます！まさしくこの箇所ですね。おそらくなのですが、awaitが付いていなかったので場合によってはコールバック内の `reply.redirect(302, '/login')` が発生せず、エラーになる人とそうでない人（筆者）がいたのではないかと思います。

こちらで修正させて頂いてももちろん構わないのですが、もしよろしければサンプルアプリケーションに Pull Request を送ってみませんか？せっかくデバッグまでしていただいたので、コントリビューションが形として残るとこちらとしても嬉しく思います。もちろん、お忙しいようでしたらこちらで修正致します。

@Gyozadaigaku ご確認ありがとうございます！解決に長く時間が掛かってしまいすみませんでした。

お二人のご協力のおかげで進展して大変ありがたく思います。ハンズオン、引き続きお楽しみください！

**Comment by ytak-sagit** [comment]
@tsuemura  
ご確認頂きありがとうございます！  
なるほどですね～。非同期処理はこの辺り、自分も落とし穴にハマりそうなので気を付けないと・・・  
  
> こちらで修正させて頂いてももちろん構わないのですが、もしよろしければサンプルアプリケーションに Pull Request を送ってみませんか？せっかくデバッグまでしていただいたので、コントリビューションが形として残るとこちらとしても嬉しく思います。もちろん、お忙しいようでしたらこちらで修正致します。
  
ご提案ありがとうございます。  
もしよければ是非とも、PR送らさせて頂きたいです！  
他方で、当方コントリビュートの形でPR送った経験がなく・・・^^;  
何点か教えて頂きたいです・・・！！
- PRのマージ先は、`main` ブランチでよろしいでしょうか。
- トピックブランチの切り方でご指定ありましたら、ご教示頂ければ幸いです。  
   - もし特になければ、`ytak-sagit/hotfix/modify-redirect-to-items-page` ブランチを切ろうかと。
- PRの内容に記載すべき事項ありましたら、ご教示頂ければ幸いです。
- 他、もしご指定等ありましたら共有ください。

**Comment by ytak-sagit** [comment]
@Gyozadaigaku  
当方の修正コードにて動作検証して頂き、ありがとうございました！大変助かりましたm(_ _)m

**Comment by tsuemura** [comment]
@ytak-sagit 

> PRのマージ先は、main ブランチでよろしいでしょうか。
はい、mainブランチ宛でお願いします。
なお、mainブランチにマージされた後、ch06以降のサンプルコードにもこちらで反映（マージ）する予定です。

> トピックブランチの切り方でご指定ありましたら、ご教示頂ければ幸いです。
> もし特になければ、ytak-sagit/hotfix/modify-redirect-to-items-page ブランチを切ろうかと。
こちらからは特に指定ございません。

> PRの内容に記載すべき事項ありましたら、ご教示頂ければ幸いです。
こちらのIssueへのリンクと、修正の意図について簡単に記載していただけますと大変ありがたいですが、あくまで書籍のサンプルですので、ご面倒でない範囲で結構です。

ちなみに、本サンプルアプリケーションでは特に指定していませんが、多くのOSSではコントリビューションガイドというものが存在しまして、今回ご質問頂いたような内容が書かれています。例えば、CodeceptJSのコントリビューションガイドはこちらです。
https://github.com/codeceptjs/CodeceptJS/blob/master/.github/CONTRIBUTING.md

既にご存知かもしれませんが、ご共有まで！

**Comment by ytak-sagit** [comment]
@tsuemura  
ご回答ありがとうございます！  
以下のPR出させて頂きました！お手すきの際にご確認をお願いいたします。  
https://github.com/tsuemura/fastify-webapp-sample/pull/2

> ちなみに、本サンプルアプリケーションでは特に指定していませんが、多くのOSSではコントリビューションガイドというものが存在しまして、今回ご質問頂いたような内容が書かれています。例えば、CodeceptJSのコントリビューションガイドはこちらです。
https://github.com/codeceptjs/CodeceptJS/blob/master/.github/CONTRIBUTING.md
> 
> 既にご存知かもしれませんが、ご共有まで！

こちらも情報共有ありがとうございます！勉強になります。  
※PRを出すにあたり、共有頂いたCodeceptJSの[PRテンプレート](https://github.com/codeceptjs/CodeceptJS/blob/master/.github/PULL_REQUEST_TEMPLATE.md)を参考にしました。  
　記載内容に不明点等ございましたらお申し付けください。

**Comment by harachanx** [comment]
@tsuemura 
> ご確認ありがとうございます！解決に長く時間が掛かってしまいすみませんでした。

とんでもないです！問題が無事解決して安心しました🙂

@ytak-sagit 
> 当方の修正コードにて動作検証して頂き、ありがとうございました！大変助かりましたm(_ _)m

修正ありがとうございました！おかげでハンズオンが進められそうです🎉
こちらこそ感謝です🥹
