### ISSUE TITLE
GitHub Pagesへ配信されたテストレポートの中身が正しくない

### ISSUE THREAD

**Issue by ytak-sagit** [tsuemura/practical-guide-for-test-automation-support#6]
### 概要

「6-5-4 GitHub Pagesでテストレポートを保存＆配信する」にて、  
GitHub Pagesへのテストレポート配信は正常終了しているが、  
レポートの中身を確認してみると、テストケース数0、NaN% のような不正な表示となっている。

![image](https://github.com/user-attachments/assets/f60775da-e9df-4b51-b92c-d27226768f63)

### 再現手順

書籍記載のYAMLファイルを使用して、ワークフローファイルを実行する

### 補足

当方でワークフローの実行ログを見たところ、`Load test report history` ステップにて、  
直前の `Run E2E test` ステップで生成した `allure-results` ディレクトリが削除されてしまっているようでした。
```bash
Cleaning the repository
  /usr/bin/git clean -ffdx
  Removing e2e/allure-results/
  Removing e2e/node_modules/
  Removing e2e/output/
```

このため、`Build test report` ステップで「`e2e/allure-results` が見つからない」旨のメッセージも出力されていました。
```bash
generating report from e2e/allure-results to allure-report ...
e2e/allure-results does not exist
```

お手数ですが、ご確認頂ければ幸いですm(_ _)m

**Comment by tsuemura** [comment]
@ytak-sagit ご報告ありがとうございます。
ちなみに、Forkしていただいたリポジトリを見ると、現在は正常に表示されているようですが、ご自身で何かお試し頂いて解決した感じでしょうか？もし差し支えなければ、試したことをご共有いただけますと大変助かります 🙇

https://ytak-sagit.github.io/fastify-webapp-sample/13/

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/124aaf81-ee92-4b62-82af-9fd3651fe58b">

**Comment by ytak-sagit** [comment]
@tsuemura  
Forkリポジトリの確認までして頂き、ありがとうございます！！  
ご認識の通り、現状は表示されるようになっております。  
  
試したこととしては、「アーティファクトを介して `allure-results` を後続stepへ受け渡す」ことを行いました。
- https://github.com/ytak-sagit/fastify-webapp-sample/pull/5#issuecomment-2283606167

`gh-pages` ブランチをチェックアウトした段階で `allure-results` が削除されてしまうので、  
「一時的に退避して後から参照できるようにしよう」...と考えた次第でした。  
（私がGitHub Actionsにあまり明るくなく、もしかしたら他に良いやり方があるかもしれませんが...）

**Comment by tsuemura** [comment]
@ytak-sagit ありがとうございます。

確かにおっしゃる通りで、 `Load test report history` の中で `/usr/bin/git clean -ffdx` が実行されている、つまり `.gitignore` に含まれているファイルを全て削除してしまっているようです。
まだ試していないのですが、おそらく以下のように `clean: ''` オプションを指定すると動作するのではないかと思います。

```
- name: Load test report history
  uses: actions/checkout@v4
  if: always()
  continue-on-error: true
  with:
    ref: gh-pages
    path: gh-pages
    clean: ''

```

参考: https://github.com/marketplace/actions/checkout?version=v3.6.0

いずれにせよ、こちらは本書の記述の誤りですので、試された内容が間違っているわけではありません。また、アーティファクトを介した方法の方がおそらく使いやすいのではないかと思うので、改訂の際はこちらを取り入れさせてください。
ご面倒をおかけしてすみません、ご報告ありがとうございました。

**Comment by ytak-sagit** [comment]
@tsuemura  
ご確認頂きありがとうございます。承知しました！  
issuesとしてはクローズさせて頂きます。
