### ISSUE TITLE
「7-6 受け取り日に動的な日付を入れる」の `utils` ディレクトリ作成位置が分かりづらい

### ISSUE THREAD

**Issue by ytak-sagit** [tsuemura/practical-guide-for-test-automation-support#7]
### 概要

「7-6 受け取り日に動的な日付を入れる」の中で `utils/index.js` を作成する箇所があります。  
書籍 p.188 のコード例では `utils/index.js` と表記されているため、プロジェクトルート直下に `utils` ディレクトリを作成するように見えます。  
しかし、`e2e/codecept.conf.js` のコード例 p.189 を読み進めると、
```diff js
  include: {
    I: "./steps_file.js",
+   utils: './utils'
  }
```
と記載があり、`e2e` ディレクトリの中で `utils` ディレクトリを作成する（`e2e/utils/` とする）必要があることが分かります。  
書籍通りに進めると、`utils/index.js` に配置したままこの次の `order_process_test.js` を実行することになり、  
テストがうまく動かず、つまずく方もいそうだな。と感じました。

### 提案

`utils` ディレクトリの作成位置が曖昧に感じますので、  
「`e2e` ディレクトリの中に `utils` ディレクトリを作成し、その中に `index.js` を作成します」  
のような補足があると、混乱が生じないかと思います。  
  
お手数ですが、ご確認・ご検討頂ければ幸いです。

**Comment by tsuemura** [comment]
@ytak-sagit ありがとうございます。
本来、以下画像の囲みのところで `e2e/utils/index.js` と表記すべきところを、 `utils/index.js` とだけ記載してしまっていますね。
こちらはご指摘の通り誤植となりますので、出版社の正誤表及び本リポジトリで記載致します。

<img border=1px width="618" alt="image" src="https://github.com/user-attachments/assets/96da2741-a052-4deb-aeec-919478d23e45">

また、本文については、残念ながらこれから修正するのは難しいのですが、もし改訂版が出る際には加えさせていただきます。文例まで付けて頂きありがとうございました。

**Comment by ytak-sagit** [comment]
@tsuemura  
ご確認頂きありがとうございます。承知しました！
issuesとしてはクローズさせて頂きます。
